# File: Makefile
# Class: CS 215
# Assignment: Practical Exam 2, Problem 1
# Date: March 28 & 30, 2017

problem1: problem1.o
	clang++ -g -Wall -o problem1 problem1.o

problem1.o: problem1.cpp
	clang++ -g -Wall -c problem1.cpp

clean:
	rm -f *.o problem1 *~
